### ISSUE TITLE
There needs to be a way to securely pass in the apiKey

### ISSUE THREAD

**Issue by mra-cfs** [coroot/coroot-operator#14]
Currently the operator only accepts a string as the value for the apiKey which makes deploying the Coroot object to client clusters via infrastructure as code insecure. Can we extend the operator to read this value from a secret on the cluster that we can then manage with ExternalSecrets or any other method of loading the secret into the cluster securely. Thank you!

**Comment by apetruhin** [comment]
Starting with Operator [v1.3.0](https://github.com/coroot/coroot-operator/releases/tag/v1.3.0), the API key can be configured using the [apiKeySecret](https://docs.coroot.com/installation/k8s-operator#coroot-cr-custom-resource) parameter:
```yaml
# The API key used by agents when sending telemetry to Coroot.
# apiKey: # Plain-text API key. Prefer using `apiKeySecret` for better security.
apiKeySecret: # Secret containing the API key.
  name: # Name of the secret to select from.
  key:  # Key of the secret to select from.
```
