### ISSUE TITLE
Operator leaks api_keys

### ISSUE THREAD

**Issue by mra-cfs** [coroot/coroot-operator#16]
The operator manifest supports managing projects, including passing in api_keys for projects as secrets:

```
  projects:
    - name: dev-blue
      apiKeys:
        - keySecret:
            name: coroot-projects
            key: dev-blue
```

But when that gets pushed to the clusters the init container leaks all of the keys:

```
  initContainers:
    - args:
        - |-
          cat <<EOF > /config/config.yaml
          projects:
          - name: dev-blue
            api_keys:
            - key: hunter1
              description: 
```

This is where that happens;
https://github.com/coroot/coroot-operator/blob/2e262c6c7a745557da58e4a7a5ca1232729e9f26/controller/coroot.go#L519-L522
