### ISSUE TITLE
How set version for coroot installed by operator?

### ISSUE THREAD

**Issue by patsevanton** [coroot/coroot-operator#17]
Hello!

in elasticsearch set version in spec
```
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: search
  namespace: search
spec:
  version: 8.14.1
```
I don't see this in coroot.

is it correct that we specify the image ourselves?
```
---
apiVersion: coroot.com/v1
kind: Coroot
metadata:
  name: coroot
  namespace: coroot
spec:
  image:
    name: ghcr.io/coroot/coroot:1.12.4
  nodeAgent:
    image:
      name: ghcr.io/coroot/coroot-node-agent:1.25.4
  clusterAgent:
    image:
      name: ghcr.io/coroot/coroot-cluster-agent:1.3.0
```
