### ISSUE TITLE
lack of nodeSelector in CRD

### ISSUE THREAD

**Issue by gecube** [coroot/coroot-operator#7]
Good day!

I want to schedule a coroot components to a dedicated nodes. The simplest approach to do it to use `nodeSelector` field. It is though supported by many other projects - like [Victoria Metrics](https://docs.victoriametrics.com/operator/api/#vmsinglespec-nodeselector) and many others. Right now Coroot does not support it in favour of nodeAffinity. Unfortunately, nodeAffinity much more complex thing.

So I am forced to write:

```yaml
...
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - monitoring
...
```

instead of simple:

```yaml
...
      tolerations:
      - key: app
        operator: Equal
        value: monitoring        
      nodeSelector:
        app: monitoring
...
```

I am kindly asking to bring support for `nodeSelector` and all other possible fields that could be useful to the users in Coroot CRD.
